sudo: required
services:
  - docker

before_install:
  - docker build -t chiranth12/git-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chiranth12/git-react npm run test

deploy:
  provider: elasticbeanstalk
  dpl_version: 1.10.16  # Preserve the current version of dpl
  region: "us-east-1"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-381825305920"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
